# Generated by Django 5.0 on 2024-01-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mashgulot_boshlanish_vaqti_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mukammal tana',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name_plural': 'Sinflar',
            },
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Biz bilan boglaning'},
        ),
        migrations.AlterModelOptions(
            name='mashgulot',
            options={'verbose_name_plural': 'Mashgulotlar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Xizmatlar'},
        ),
    ]
