# Generated by Django 5.0 on 2024-01-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_body_class_alter_contact_us_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_icon',
            field=models.ImageField(default=1, upload_to='items/'),
            preserve_default=False,
        ),
    ]
